# Generated by Django 4.0.5 on 2022-07-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_alter_author_birth_year_alter_author_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['full_name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
